export enum ACTIONS {
  ADD_SYNONYM = 'EDIT_ADD_SYNONYMSYNONYM',
  CHANGE_NAME_INPUT_VALUE = 'CHANGE_NAME_INPUT_VALUE',
  CLEAR_SYNONYMS = 'CLEAR_SYNONYMS',
  CLOSE_POPUP = 'CLOSE_POPUP',
  DELETE_SYNONYM = 'DELETE_SYNONYM',
  EDIT_SYNONYM = 'EDIT_SYNONYM',
  EDIT_SYNONYM_CANCEL = 'EDIT_SYNONYM_CANCEL',
  EDIT_SYNONYM_SAVE = 'EDIT_SYNONYM_SAVE',
  GET_SYNONYMS = 'GET_SYNONYMS',
  OPEN_POPUP = 'OPEN_POPUP',
  SAVE_CHANGES = 'SAVE_CHANGES',
}
